### PR TITLE
pull request

### PR DESCRIPTION
**Pull request by expectopatronum**
Hi,
I am not sure if it was the right thing to open a fork, I am not very used to github yet ;) But I can change that.

Best regards,
Verena

### CODE REVIEW

**Comment by Ironholds** [comment]
Thankya! A couple of tweaks:
1. Don't forget to add documentation for the new parameters to the functions.
2. You should update NEWS, and DESCRIPTION. Specifically, add yourself as name [ctb]. Code contributions deserve credit :D

**Comment by expectopatronum** [comment]
Hi,

ah ok, added the documentation!
Where exactly can I add my name? Should date/version also be updated or
does this only happen when it's released to CRAN?

**Comment by Ironholds** [comment]
The Author field! Should be changed to:

> Author: Oliver Keyes [aut, cre], $name [ctb]

Yeah, I'll bump the date and version on the CRAN release :)

**Comment by expectopatronum** [comment]
ok, did it! :)

**Comment by Ironholds** [comment]
Danke! :D

**Pull request merged**
